### ISSUE TITLE
cli not working for me

### ISSUE THREAD

**Issue by evan-forbes** [daneads/pycallgraph2#8]
thanks for reviving an awesome project!!

This feels like a simple mistake on my part... so I have followed all of the instructions on the intro page, and am sure that pycallgraph2 and graphviz are installed, but I still cannot use the cli. 
getting 
No command 'pycallgraph2' found, did you mean:
 Command 'pycallgraph' from package 'python-pycallgraph' (universe)
pycallgraph2: command not found

Also the api is not producing a png or raising any errors.

thanks ahead of time!

**Comment by asciidoc3** [comment]
The same for me ...

**Comment by CromFr** [comment]
this has been fixed by PR #6, but there has been no release on pypi since

**Comment by daneads** [comment]
Thanks all, you should be able to update via today's PyPi release.

**Comment by ARF1** [comment]
@asciidoc3 For me this is not fixed. Also I cannot see where in #6 any fix would have happended. Maybe something was overlooked in staging #6?

**Comment by evan-forbes** [comment]
closing this ancient issue
